inactive-opacity = 0.85
active-opacity = 1.0
blur-method = "dual_kawase"
blur-strength = 5
corner-radius = 12
animations = true
animations-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-stiffness = 300.0;
